/* AUTH ACTIONS */
export const AUTH_STATE_BUSY = "AUTH_STATE_BUSY"
export const AUTH_STATE_FAILED = "AUTH_STATE_FAILED"
export const AUTH_STATE_SUCCESS = "AUTH_STATE_SUCCESS";

/////service actions
export const SERVICE_STATE_SUCCESS = "SERVICE_STATE_SUCCESS";
export const SERVICE_STATE_BUSY = "SERVICE_STATE_BUSY";
export const SERVICE_STATE_FAILED = "SERVICE_STATE_FAILED";
